# Generated by Django 2.1.4 on 2019-01-24 18:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('predictions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('errors', models.CharField(max_length=255)),
                ('date_stored', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
